tasks:
  - init: sh syncmaster.sh && sh install.sh
  - command: cd piattaforma-scuola-backend && yarn start:dev
  - command: cd piattaforma-scuola-frontend && yarn dev
ports:
  - port: 3000
  - port: 3001
    onOpen: open-preview
image:
  file: .gitpod.Dockerfile
