tasks:
  - before: cd piattaforma-scuola-frontend
    init: >
     git fetch origin 
     ; git checkout master 
     ; git merge origin/master 
     ; yarn install
     ; gp sync-done frontendInstall
    command: yarn dev --host
  - before: cd piattaforma-scuola-backend
    init: >
     cd piattaforma-scuola-backend
     ; git fetch origin ; git checkout master
     ; git merge origin/master
     ; gp sync-await frontendInstall
     ; yarn install
     ; cp example.env .env
    command: cd piattaforma-scuola-backend ; yarn start:dev
ports:
  - port: 3000
  - port: 3001
    onOpen: open-preview
image: gitpod/workspace-mongodb
